# Inserts a blank line between shell prompts
add_newline = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"

[character]                            
success_symbol = "[â†ªï¸](bold green)"
error_symbol = "[âœ–](bold red) "

[directory]
truncate_to_repo = false

[hostname]
ssh_only = true
format = "[$hostname]($style):"
trim_at = "-"
style = "bold purple"
disabled = false

[username]
format = "[$user]($style)[@](bold blue)"
style_user = "bold yellow"
show_always = false

